# Comment to trigger commit in VSCode Extension
version: 2.1
orbs:
  python: circleci/python@2.1.1
  datadog-agent: datadog/agent@3.2.0

workflows:
  evaluate-commit:
    jobs:
      - run-commit-evals:
          context:
            - ai-eval-examples
            - OpenAI

jobs:
  run-commit-evals:
    docker:
      - image: cimg/python:3.11.9-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - datadog-agent/setup:
          agent_major_version: '7'
          api_key: DD_API_KEY
          site: datadoghq.com
      - run:
          name: Run assistant evals.
          command: python -m pytest --junitxml results.xml test_hallucinations.py
      - datadog-agent/stop
      - store_test_results:
          path: results.xml
