version: 2.1
orbs:
  python: circleci/python@2.1.1

workflows:
  evaluate-commit:
    jobs:
      - run-commit-evals:
          context:
            - OpenAI

jobs:
  run-commit-evals:
    docker:
      - image: cimg/python:3.10.5
    resource_class: medium
    parallelism: 2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run assistant evals.
          command: |
            set -e
            TESTFILES=$(circleci tests glob "**/test_hallucinations*.py" | circleci tests split)
            python -m pytest --junitxml results.xml $TESTFILES
      - store_test_results:
          path: results.xml
